### ISSUE TITLE
Sort Chat list by recent message and  Mobile version

### ISSUE THREAD

**Issue by thekamalkashyap** [Ajay-056/Whatsapp-Clone-NextJS#38]
hey brother i loved the you way added features to Sonny Sangha's whatsapp clone. i appreciate your work and i think i can help you in implementing mobile friendly view and sorting chats by recent messages. so do you want me to work on that?

**Comment by Ajay-056** [comment]
Hey Kamal, Thanks. Really good to meet you I'm a Linux freak too. Saw your works its great. I was once interested in development. But not anymore I'm not spending time on this. My codebase is little messed up. But your contribution is always welcome and thanks for showing interest on this. Please reach me in twitter (profile in my bio).

**Comment by thekamalkashyap** [comment]
sure brother i'll reach you on Twitter 😊 and also i am facing problem in implementing date wise sorting of chats so can you help me with that 😛🤣
